//Diccionario con descripción de variables:

var dict={
	m={//meteorologia
           id:"ID de estación meteorológica",
           nombre:"Nombre de estación",
           tmin:"Temperatura mínima [grados Kelvin]",
           tmax:"Temperatura maxima [grados Kelvin]",
           u:"Velocidad de viento promedio [m/s]",
           i:"Insolación [Watt/m2]",		//!!OJO AVERIGUAR BIEN QUE SE USA Y QUE UNIDADES!!
           p:"Presión atmosferica [hPa]",
	},
	l={//liquido/combustible
          nombre:"Nombre del compuesto",
          cas:"CAS",
          m_l:"Molecular weight of liquid mixture, lb/lb-mole",
          w_l:"Average organic liquid density, lb/gal",
          s:"Solpe",
          vpt:"Vapor pressure at average daily liquid surface temperature, psia",
          A:"Constant in vapor pressure equation, dimensionless",
          B:"Constant in vapor pressure equation, dimensionless",
          C:"Constant in vapor pressure equation, dimensionless",
          //Tmax,Tmin,N_BP No aparecen en los cálculos ni dice en el codigo que son.
	},
	t={//tanque
		tipo:"(VFR|HFR|EFR|IFR)",
                H:"altura del tanque [m]",
                D:"diametro del tanque [m]",
                minLvl:"altura minima de liquido [m]",
                avgLvl:"altura promedio de liquido [m]",
                maxLvl:"altura maxima de liquido [m]",
                turnovers:"numero de turnovers",
                vaporbalanced:"esta en equilibrio con el vapor?",

                shell:{
                        color:"color de la cubierta",
                        condition:"(new|aged|average)",
                        insulation:"aislamiento termico?",
                },
                roof:{
                        type:"(cone|dome)",
                        color:"color del techo",
                        condition:"(new|aged|average)",
                        height:"altura del techo [m]",
                        insulation:"aislamiento térmico?",
                },
                heating:{
                        heating:"considerar calentamiento?",
                        n_cycles_per_year:"numero de ciclos de calentamiento",
                        min_liq_temp:"temperatura minima del liquido [grados Kelvin]",
                        max_liq_temp:"temperatura maxima del liquido [grados Kelvin]",
                },
		a:"Absorbancia solar de la superficie del tanque [-]", 
	},
	o={//salidas

	},
};


//
//Diccionario ORIGINAL con descripción de variables:
var dict_original= {
	a:"Tank surface solar absorptance, dimensionless", 
	a_R:"Tank roof surface solar absorptance, dimensionless",
	a_S:"Tank shell surface solar absorptance, dimensionless", 
	A:"Constant in vapor pressure equation, dimensionless", 
	A_deck:"Area of deck, ft2", 
	A_fi:"Liquid surface area within a particular type of deck fitting, in2", 
	B:"Constant in vapor pressure equation, °R or °C", 
	C:"Constant in vapor pressure equation, °R or °C", 
	C_S:"Shell clingage factor, bbl/1,000 ft2", 
	C_sf:"Filling saturation correction factor for wind, dimensionless", 
	C_V:"Average vapor concentration by volume during continued forced ventilation, dimensionless", 
	D:"Tank diameter, ft", 
	D_E:"Effective tank diameter, ft", 
	d_s:"Average depth of sludge, in.", 
	F_C:"Effective column diameter, ft", 
	F_E:"Fraction of sludge with potential to evaporate, dimensionless", 
	F_F:"Total deck fitting loss factor, lb-mole/yr", 
	h_d:"Deck leg height at the tank shell, ft", 
	H_L:"Liquidd height, ft", 
	h_le:"Effective liquid height during roof landing, ft", 
	H_LN:"Minimum liquid height, ft", 
	H_LX:"Maximum liquid height, ft", 
	sumH_QD:"Annual sum of the decreases in liquid level, ft/yr", 
	sumH_QI:"Aannual sum of the increases in liquid level, ft/yr", 
	H_R:"Tank roof height, ft", 
	H_RO:"Roof outage, ft", 
	H_S:"Tank shell height, ft", 
	h_v:"Vapor space height under landed floating roof, ft", 
	H_VO:"Vapor space outage, ft", 
	I:"Average daily total insolation factor, Btu/ft<sup>2</sup>•d", 
	K_C:"Product factor for floating roof tanks, dimensionless", 
	K_D:"Deck seam loss per unit seam length factor, lb-mole/ft-yr", 
	K_E:"Vapor space expansion factor, per day", 
	K_Fai:"Zero wind speed loss factor for a particular type of deck fitting, lb-mole/yr", 
	K_Fbi:"Wind speed dependent loss factor for a particular type of deck fitting, lb-mole/(mph)myr", 
	K_Fi:"Loss factor for a particular type of deck fitting, lb-mole/yr", 
	K_N:"Turnover factor, dimensionless", 
	K_P:"Working loss product factor for fixed roof tanks, dimensionless", 
	K_Ra:"Zero wind speed rim seal loss factor, lb-mole/ft•yr", 
	K_Rb:"Wind speed dependent rim seal loss factor, lb-mole/ (mph)nft•yr", 
	K_S:"Vented vapor saturation factor, dimensionless", 
	K_v:"Fitting wind speed correction factor, dimensionless", 
	L:"Length of tank, ft", 
	L_C:"Clingage factor for drain dry tanks, lb", 
	L_CV:"Continued forced ventilation emissions, lb/cleaning event", 
	L_D:"Deck seam loss, lb/yr", 
	L_F:"Deck fitting loss, lb/yr", 
	L_FV:"Total tank cleaning emissions due to forced ventilation, lb/cleaning event", 
	L_FL:"Filling loss during roof landing, lb/landing event", 
	L_P:"Vapor space purge emissions due to first air change from forced ventilation, lb/cleaning event", 
	L_R:"Rim seal loss, lb/yr", 
	L_RL:"Rim seal loss during roof landing, lb/landing event", 
	L_S:"Standing losses, lb/yr", 
	L_seam:"Total length of deck seam, ft", 
	L_SL:"Standing loss during roof landing, lb/landing event", 
	L_T:"Total routine losses, lb/yr", 
	L_Ti:"Emission rate of component i, lb/yr", 
	L_TL:"Total loss during roof landing, lb/landing event", 
	L_V:"Variable vapor space filling loss, lb/1,000 gal throughput", 
	L_W:"Working losses, lb/yr", 
	M_CG:"Molecular weight of calibration gas, lb/lb-mole", 
	m_i:"Loss factor for a particular type of deck fitting, dimensionless", 
	M_i:"Molecular weight of component i, lb/lb-mole", 
	M_L:"Molecular weight of liquid mixture, lb/lb-mole", 
	M_V:"Vapor molecular weight, lb/lb-mole", 
	N:"Number of turnovers per year, dimensionless", 
	n:"Seal-related wind speed exponent, dimensionless", 
	n_d:"Number of days standing idle during roof landing or prior to forced ventilation, days", 
	N_2:"Number of transfers into system, dimensionless", 
	N_C:"Number of columns, dimensionless", 
	n_CV:"Duration of continued forced ventilation, days", 
	N_d:"Number of drains", 
	n_f:"Total number of different types of fittings, dimensionless", 
	N_Fai:"Zero wind speed loss factor for a particular type of deck fitting, lb-mole/yr", 
	N_Fbi:"Wind speed dependent loss factor for a particular type of fitting, lb-mole/mphm•yr", 
	N_Fi:"Number of deck fittings of a particular type, dimensionless", 
	N_l:"Number of deck legs", 
	N_TOTAL:"Total number of moles in mixture, lb-mole", 
	N_vb:"Number of vacuum breakers", 
	P:"True vapor pressure of component i, psia", 
	P_star:"Vapor pressure function, dimensionless", 
	P_A:"Atmospheric pressure, psi", 
	deltaP_B:"Breather vent pressure setting range, psig", 
	P_BP:"Breather vent pressure setting, psig", 
	P_BV:"Breather vent vacuum setting, psig", 
	P_I:"Gauge pressure within the vapor space, psig", 
	P_i:"Partial pressure of component i, psia", 
	deltaP_V:"Average daily vapor pressure range, psi", 
	P_VA:"Vapor pressure at average daily liquid surface temperature, psia", 
	P_VN:"Vapor pressure at the average daily minimum liquid surface temperature, psia", 
	P_VX:"Vapor pressure at the average daily maximum liquid surface temperature, psia", 
	Q:"Annual net throughput, bbl/yr", 
	Q_V:"Average ventilation rate during tank cleaning, ft3/min", 
	R:"Ideal gas constant, psia•ft<sup>3</sup>/lb-mole•&deg;R", 
	R_R:"Tank dome roof radius, ft", 
	R_S:"Tank shell radius, ft", 
	S:"Filling saturation factor, dimensionless", 
	s:"Tank cone bottom slope, ft/ft", 
	S_D:"Deck seam length factor, ft/ft2", 
	S_R:"Tank cone roof slope, ft/ft", 
	deltaT_A:"Average daily ambient temperature range, °R", 
	T_AA:"Average daily ambient temperature, °R", 
	T_AN:"Average daily minimum ambient temperature, °R", 
	T_AX:"Average daily maximum ambient temperature, °R", 
	T_B:"Liquid bulk temperature, °R", 
	T_BN:"Typical minimum liquid bulk temperature in heating cycles, °R", 
	T_BX:"Typical maximum liquid bulk temperature in heating cycles, °R", 
	T_LA:"Average daily liquid surface temperature, °R", 
	T_V:"Average vapor temperature, °R", 
	t_v:"Daily period of forced ventilation during tank cleaning, hr/day", 
	deltaT_V:"Average daily vapor temperature range, °R", 
	v:"Average wind speed, mph", 
	V_1:"Volume of liquid pumped into system, bbl/yr", 
	V_2:"Volume expansion capacity, bbl", 
	V_Q:"Net working loss throughput, ft<sup>3</sup>/yr", 
	V_LX:"Tank maximum liquid volume, ft<sup>3</sup>", 
	V_V:"Vapor space volume, ft<sup>3</sup>", 
	W_i:"Liquid density of component i, lb/ft<sup>3</sup>", 
	W_L:"Average organic liquid density, lb/gal", 
	W_V:"Vapor density, lb/ft<sup>3</sup>", 
	x_i:"Liquid mole fraction of component i, lb-mole/lbmole", 
	y_i:"Vapor mole fraction of component i, lb-mole/lbmole", 
	Z_Li:"Liquid weight fraction of component i, lb/lb", 
	Z_Vi:"Vapor weight fraction of component i, lb/lb"
};
